setup and mobile first
sulaimanahmadi/MyPortfolio pull request #1
Opened 2023-03-24 12:20 UTC by sulaimanahmadi

1. use of Html and CSS
2. Implement the button interactions
3. The website should be responsive
4. Use of flexbox

2023-03-24 13:36 UTC, TadesseDev requested changes
### Hi @sulaimanahmadi 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
- [ ] Please consider Updating the Microverse logo and text with yours if possible or remove it totally. The template is designed by Microverse for us all to use to professionally document our projects and has it filled with content related to each project we may be working on.
- [ ] Please consider removing non-important contents from your readme, The template is designed by Microverse for us all to use to document our projects professionally and has it filled with content related to each project we may be working on. currently, I can see you have not removed the guiding contents  which start with `>` and `directions set by Microverser`

You have submitted a project that has linter tests falling. Please make sure all linters are set up and passing before your next review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-24 15:18 UTC, sulaimanahmadi commented on README.md
> +
Here for me it does not show me any errors regarding linters.
![Screenshot_2023-03-24-19-42-42-041_com android chrome](https://user-images.githubusercontent.com/119625098/227566981-660438db-d20c-48fa-8bc2-4cc60b0da61f.jpg)

2023-03-25 19:55 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @sulaimanahmadi  :wave: 

Well done. :+1:  
You need to fix some issues before moving to the next project. :running_man: 

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Linters checks are passing.
✔️ Readme is professional.


## Required Changes ♻️

> Kindly check the inline comments for review.

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 19:55 UTC, Tufahel commented on style.css
> +}
- [ ] You can see, the `icon` section has more space on the left. Kindly decreased the spaces to match the given design.

- Your design:
- ![image](https://user-images.githubusercontent.com/60083437/227738392-6a25611e-6e61-49ce-b711-9c29a6cdb7d8.png)

- Given design:
- ![image](https://user-images.githubusercontent.com/60083437/227738550-bf887f4b-8c37-4eaf-9a79-a51ffa644b3f.png)

2023-03-25 19:55 UTC, Tufahel commented on style.css
> +}
- [ ] There is more gaps/padding/margin between `h1` and `h2` tags in your design, that doesn't match with the actual design. Kindly fix that issue by decreasing gaps.

- Your design:
- ![image](https://user-images.githubusercontent.com/60083437/227738681-24a263a4-fa4e-4cc1-b117-041556130691.png)

2023-03-25 20:35 UTC, MeqdamAlqudah reviewed
Hi @sulaimanahmadi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-29 15:15 UTC, closed without merging