make the mobile version portfolio
sulaimanahmadi/MyPortfolio pull request #4
Opened 2023-03-30 18:08 UTC by sulaimanahmadi

Implement the button interactions
Use of Flex and Grid
Use of CSS and Html

2023-03-30 18:44 UTC, Trast00 requested changes
# Require Change ♻️ 
Hi @sulaimanahmadi , 

Great job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there-reach](https://user-images.githubusercontent.com/74411135/225062441-793da0f4-3ef1-4d98-bee9-9c200c7121a7.gif)

## Highlights
- All linters pass 🍏 
- Professional documented project 📖 

## Required Changes ♻️
_Check the comments under the review._

- Please consider implementing all the change I left below (inline comment)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@Trast00) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 18:44 UTC, Trast00 commented on style.css
> +}
- [ ] Please consider using the grid to layout elements in your work section (even for the mobile version). This will make your project more maintainable as the grid is an incredible tool to improve responsiveness 😄

2023-04-01 09:33 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @sulaimanahmadi 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- You just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 09:33 UTC, AbelG101 commented on style.css
> +}
- [ ] As suggested by the previous reviewer kindly make sure you have a `grid` display for the container of your project cards 🎯

2023-04-01 09:33 UTC, AbelG101 commented on style.css
> +}
- [ ] Great job making the changes here but as suggested by the previous reviewer please make sure you're following the given Figma design when styling the components.
      ![image](https://user-images.githubusercontent.com/104968236/229277196-577897a0-e14a-4717-919d-d6f166a10d98.png)
    - As you can see in the design there's no `border` and the texts are aligned to the center so kindly make sure you fix that ✔.

2023-04-01 09:33 UTC, AbelG101 commented on index.html
> +        </div>
- [ ] As suggested by the previous reviewer please replace the `div` element with the `about-me-2` class name with a `ul` tag and replace the `div` element with the `grid-1, grid-2, grid-3` class name with a `li` tag (this applies for each of them). This will ensure you're following the proper semantics and gives your website a better SEO. ✔
- > * [ ]  Please update the project so language, framework and skill are `li` wrapped in a `ul`. This will make your code look much cleaner 🧼 and maintainable 😄
> 
> 
> These one should be `ul` and `li` (grid-x) ![image](https://user-images.githubusercontent.com/74411135/228933424-f28cd261-933f-4edc-9ddd-6a254c55d827.png)

2023-04-01 09:33 UTC, AbelG101 commented on index.html
- [ ] [OPTIONAL] I noticed there was a space when scrolling to the right of your website I kindly advise you to fix that as it's making your portfolio look unprofessional  👶.
      ![Inkedfirefox_x52jorRTtB](https://user-images.githubusercontent.com/104968236/229278154-7c8a1046-96d4-424e-b7a5-09b50bbb8fcf.jpg)
   - This negative space exists throughout the portfolio...

2023-04-01 14:24 UTC, sulaimanahmadi commented on index.html
Hello Dear 
I do not see any negative space throughout my portfolio here on my computer.
![portfolio](https://user-images.githubusercontent.com/119625098/229294986-89a7f7c8-3416-4149-aa42-57d75f03fedf.PNG)

2023-04-01 15:19 UTC, sulaimanahmadi commented
@AbelG101

2023-04-01 16:47 UTC, adel-gu approved these changes
# Status: APPROVED 🟢 

Hi @sulaimanahmadi 👋🏼 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Semantic tags are used for the about section content ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 16:52 UTC, adel-gu commented on index.html
Hi @sulaimanahmadi 👋🏼 

It's there actually on specific screen sizes that white space on the right side.
![image](https://user-images.githubusercontent.com/68030297/229303971-be036d21-a731-45f2-9261-fb61c77969a0.png)
![image](https://user-images.githubusercontent.com/68030297/229303972-1cda7340-6fb8-4bd7-89bd-5c3ee00f7ee1.png)

2023-04-04 07:54 UTC, merged