add a contact form
sulaimanahmadi/MyPortfolio pull request #5
Opened 2023-04-04 08:47 UTC by sulaimanahmadi

**Add following things**
1. add a contact form.
2. Collect data by using the Formspree services.
3. Implement the button interactions.

2023-04-04 08:55 UTC, AbayomiOlaoye requested changes
Hi @sulaimanahmadi :wave:, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![invalid](https://user-images.githubusercontent.com/99715640/211858554-39090b6b-2f0f-45dd-b5e0-8fb805e56431.gif)

## Invalid Code Review Request

You have submitted a pull request with no commit history from your partner. This is a pair-programing activity that is intended to ensure you work together with all your partners, as you also do the same in their repositories. This prepares you to co-work effectively in a team.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-04 17:54 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @sulaimanahmadi, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- Form uses the action and method attribute to integrate with [formspree service](https://formspree.io/html). ✔️
- Input fields have the `required` attribute to activate the validation ✔️
- Max-length attribute Used on the input ✔️
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 17:54 UTC, brainconnect93 commented on style.css
> +
- [ ] Great effort working on the `contact section` of the portfolio project, the form spree and every other things works really fine, but i notice the design and alignment of your `text` and `form` requires an attention. please kindly make sure the whole text and form are aligned centered and be sure it looks like what we have in the Figma design 👏 

| Your Design 👇  | Figma Design 👇 |
| ------------- | ------------- |
| ![form](https://user-images.githubusercontent.com/78634841/229876152-39c79683-096c-485f-b147-b0592bd2ea6e.png) | ![temp-real](https://user-images.githubusercontent.com/78634841/229876242-5a244b67-eee8-46b5-bf9d-7f8fabbce36b.png) |

2023-04-05 08:05 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @sulaimanahmadi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 17:49 UTC, merged